apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: disturbing-plum-caterpillar
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disturbing-plum-caterpillar 
  name: disturbing-plum-caterpillar
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: disturbing-plum-caterpillar 
